# Generated by Django 5.2.3 on 2025-07-02 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_article_status_alter_article_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата публикация'),
        ),
    ]
