# Generated by Django 5.2.3 on 2025-07-02 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_article_published_at'),
        ('webapp', '0003_blog_article_blog'),
    ]

    operations = [
    ]
