# Generated by Django 5.2.3 on 2025-07-09 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_tag_articletag_article_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='tags',
            new_name='old_tags',
        ),
    ]
