# Generated by Django 5.2.3 on 2025-07-09 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_rename_tags_article_old_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='articles', to='webapp.tag', verbose_name='Теги'),
        ),
        migrations.AlterField(
            model_name='article',
            name='old_tags',
            field=models.ManyToManyField(blank=True, related_name='articles_old', through='webapp.ArticleTag', through_fields=('article', 'tag'), to='webapp.tag', verbose_name='Теги'),
        ),
    ]
