# Generated by Django 5.2.3 on 2025-07-09 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_auto_20250709_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='old_tags',
        ),
        migrations.DeleteModel(
            name='ArticleTag',
        ),
    ]
