# Generated by Django 5.2.3 on 2025-07-09 13:21

from django.db import migrations


def create_default_tags(apps, schema_editor):
    Tag = apps.get_model('webapp.Tag')
    Tag.objects.bulk_create([Tag(title="test1"), Tag(title="test2"), Tag(title="test3")])


def rollback(apps, schema_editor):
    Tag = apps.get_model('webapp.Tag')
    Tag.objects.filter(title__in=("test1", "test2", "test3")).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('webapp', '0008_remove_article_old_tags_delete_articletag'),
    ]

    operations = [
        migrations.RunPython(create_default_tags, rollback)
    ]
