# Generated by Django 5.2.3 on 2025-08-27 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_article_likes_comment_likes'),
        ('webapp', '0009_rename_new_tags_article_tags'),
    ]

    operations = [
    ]
