# Generated by Django 5.2.3 on 2025-07-09 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_create_default_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='tags',
            new_name='tags_old',
        ),
    ]
