# Generated by Django 5.2.3 on 2025-07-09 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_rename_tags_article_tags_old'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Теги'),
        ),
    ]
