# Generated by Django 5.2.3 on 2025-07-09 13:33

from django.db import migrations


def transfer_tags(apps, schema_editor):
    Article = apps.get_model('webapp.Article')

    for article in Article.objects.all():
        article.tags = " ".join(list(article.tags_old.all().values_list('title', flat=True)))
        article.save()


def rollback(apps, schema_editor):
    Article = apps.get_model('webapp.Article')
    Tag = apps.get_model('webapp.Tag')

    for article in Article.objects.all():
        tags = article.tags.split()
        for tag in tags:
            new_tag, _ = Tag.objects.get_or_create(title=tag)
            article.tags_old.add(new_tag)
        article.save()

class Migration(migrations.Migration):
    dependencies = [
        ('webapp', '0011_article_tags'),
    ]

    operations = [
        migrations.RunPython(transfer_tags, rollback)
    ]
