# Generated by Django 5.2.3 on 2025-07-09 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_auto_20250709_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='tags_old',
        ),
    ]
